name: 'Command Launcher Package Action'
description: 'Automate Command Launcher package lifecycle - validate manifests, create .pkg releases, and publish to OCI registries'
author: 'Alexander Mazurov'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  packages-directory:
    description: 'Directory containing packages. Empty (default) = auto-detect: single package (root has manifest.mf) or multi-package (scan subdirectories). Set to specific path for multi-package repos with custom structure.'
    required: false
    default: ''

  validate-only:
    description: 'Only validate manifests without packaging'
    required: false
    default: 'false'

  package-format:
    description: 'Package format: zip (creates ZIP archives), oci (pushes to OCI registry), or both'
    required: false
    default: 'zip'

  oci-registry:
    description: 'OCI registry hostname (e.g., ghcr.io)'
    required: false
    default: 'ghcr.io'

  packages-namespace:
    description: 'Packages namespace path in OCI registry. Defaults to repository name (owner/repo) when empty'
    required: false
    default: ''

  oci-username:
    description: 'OCI registry username. Defaults to GitHub actor when empty'
    required: false
    default: ''

  oci-token:
    description: 'OCI registry token/password. Defaults to GITHUB_TOKEN env var if set'
    required: false
    default: ''

  force-release:
    description: 'Force recreate releases by deleting existing releases and tags first (default: false)'
    required: false
    default: 'false'

outputs:
  validated-packages:
    description: 'JSON array of validated package directories'

  valid-count:
    description: 'Number of valid packages'

  invalid-count:
    description: 'Number of invalid packages'

  packaged-artifacts:
    description: 'JSON array of created artifact paths with metadata'

  package-count:
    description: 'Number of packages created'

runs:
  using: 'node20'
  main: 'dist/index.js'
